//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lib
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Books : INotifyPropertyChanged
    {
        private string _iD_Book;
        private string _name;
        private string _iD_Company;
        private DateTime? _year;
        private string _iSBN;
        private string _description;
        private string _iD_Genre;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Books()
        {
            this.Authors = new HashSet<Authors>();
        }

        public string ID_Book
        {
            get { return _iD_Book; }
            set
            {
                _iD_Book = value;
                OnPropertyChanged("ID_Book");
            }
        }
        public string Name
        {
            get { return _name; }
            set
            {
                _name = value;
                OnPropertyChanged("Name");
            }
        }
        public string ID_Company
        {
            get { return _iD_Company; }
            set
            {
                _iD_Company = value;
                OnPropertyChanged("ID_Company");
            }
        }
        public Nullable<System.DateTime> Year
        {
            get { return _year; }
            set
            {
                _year = value;
                OnPropertyChanged("Year");
            }
        }
        public string ISBN
        {
            get { return _iSBN; }
            set
            {
                _iSBN = value;
                OnPropertyChanged("ISBN");
            }
        }
        public string Description
        {
            get { return _description; }
            set
            {
                _description = value;
                OnPropertyChanged("Description");
            }
        }
        public string ID_Genre
        {
            get { return _iD_Genre; }
            set
            {
                _iD_Genre = value;
                OnPropertyChanged("ID_Genre");
            }
        }

        public virtual Genres Genres { get; set; }
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Authors> Authors { get; set; }

        public event PropertyChangedEventHandler PropertyChanged;
        public void OnPropertyChanged(string prop = "")
        {
            if (PropertyChanged != null)
                PropertyChanged(this, new PropertyChangedEventArgs(prop));
        }
    }
}
